### ISSUE TITLE
Creating post not working in prod

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/doublehranch#129]
Create action does exist, but currently has server error:

Paperclip::Errors::CommandNotFoundError (Could not run the `identify` command. Please install ImageMagick.)

**Comment by maebeale** [comment]
To work on this, you'd need to be granted Heroku access to the repo.

**Comment by kalimar** [comment]
Fixed! Required cleaning up buildpacks on Heroku, adding a config file for `production.rb` and adding AWS credentials to production.
