### ISSUE TITLE
Grapevine search should search positions (years and position titles)

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/doublehranch#131]
Seems like only name & email searches are currently working?

**Comment by jwpincus** [comment]
I can take a crack at this.

**Comment by jwpincus** [comment]
I'm willing to take a crack at this.
After doing a little bit of digging: it doesn't seem like there is an association for users to have a year. Is this meant to be a reference to the year that they held a position?

**Comment by jwpincus** [comment]
Ok. This PR will will add the ability to search by position. https://github.com/rubyforgood/doublehranch/pull/143
