### ISSUE TITLE
Hover State is too subtle for these old eyes [Discussion]

### ISSUE THREAD

**Issue by kalimar** [rubyforgood/doublehranch#136]
Throwing it out there: My eyes are too old for the green change here:

![screen shot 2017-07-03 at 10 51 14 am](https://user-images.githubusercontent.com/1248672/27797980-97639486-5fdd-11e7-8732-c40a6aa47a10.png)
(Hover)

![screen shot 2017-07-03 at 10 52 04 am](https://user-images.githubusercontent.com/1248672/27798007-ad202758-5fdd-11e7-9278-058553cd3a0b.png)
(normal)

Any thoughts?

**Comment by maebeale** [comment]
@kalimar yup, agree it could have more contrast. i recently added some more, but not sure it is enough?

**Comment by kalimar** [comment]
Looks fine to me!
